version: '2'

services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password1234567890!"
    ports:
      - "1433:1433"
